---

apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: conformance
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: getambassador.io/ingress-controller